// =============================================================================
// Inspection Capture Types
// =============================================================================

export type InspectionStatus = 
  | 'Draft'
  | 'In Progress'
  | 'Submitted'
  | 'Office Review'
  | 'Corrections Requested'
  | 'Ready for Report'
  | 'Report Generated'

export type SyncStatus = 
  | 'synced'
  | 'queued'
  | 'syncing'
  | 'failed'

export interface SyncState {
  status: SyncStatus
  lastSyncedAt?: string
  error?: string
  retryCount?: number
}

// Checklist categories for tank inspection
export const CHECKLIST_CATEGORIES = [
  'wet_interior',
  'exterior',
  'foundation',
  'anchor_bolts',
  'overflow',
  'manway',
  'ladder',
  'safety_climb',
  'vent',
  'hatch',
  'aviation_light',
  'cables',
  'catwalk',
  'coatings',
] as const

export type ChecklistCategory = typeof CHECKLIST_CATEGORIES[number]

export interface ChecklistSection {
  category: ChecklistCategory
  photos: InspectionPhoto[]
  measurements: SectionMeasurement[]
  notes: string
  hasDeficiency: boolean
  deficiencySeverity?: 'minor' | 'moderate' | 'severe'
  isComplete: boolean
  isRequired: boolean
}

export interface InspectionPhoto {
  id: string
  file?: File
  url?: string
  thumbnailUrl?: string
  category: ChecklistCategory | 'general' | 'measurement'
  caption?: string
  takenAt: string
  takenBy: string
  isRequired: boolean
  measurementId?: string // Link to measurement if it's a measurement photo
}

export interface SectionMeasurement {
  id: string
  type: string
  value?: number
  unit: string
  notes?: string
  photos: InspectionPhoto[]
}

// Priority measurements required for all inspections
export const PRIORITY_MEASUREMENTS = [
  { type: 'overflow_size', label: 'Overflow Size', unit: 'in' },
  { type: 'hatch_size', label: 'Hatch Size', unit: 'in' },
  { type: 'manway_size', label: 'Manway Size', unit: 'in' },
  { type: 'vent_size', label: 'Vent Size', unit: 'in' },
  { type: 'standpipe_diameter', label: 'Standpipe Diameter', unit: 'in' },
  { type: 'standpipe_height', label: 'Standpipe Height', unit: 'ft' },
] as const

export type MeasurementType = typeof PRIORITY_MEASUREMENTS[number]['type']

export interface InspectionMeasurement {
  type: MeasurementType
  value?: number
  unit: string
  notes?: string
  photos: InspectionPhoto[]
}

export interface Inspection {
  name: string
  customer: string
  customerName: string
  site: string
  siteName: string
  tank: string
  tankName: string
  tankType: string
  crew: string
  crewName: string
  serviceDate: string
  weather?: string
  temperature?: number
  language: 'en' | 'es'
  status: InspectionStatus
  syncState: SyncState
  currentStep: number
  
  // Step 1: Context confirmation
  contextConfirmed: boolean
  initialPhoto?: InspectionPhoto
  
  // Step 2: Checklist sections
  sections: Record<ChecklistCategory, ChecklistSection>
  
  // Step 3: Priority measurements
  measurements: InspectionMeasurement[]
  
  // Step 4: Bulk upload photos
  bulkPhotos: InspectionPhoto[]
  unassignedPhotos: InspectionPhoto[]
  
  // Step 5: Validation & submission
  waivers: ValidationWaiver[]
  submittedAt?: string
  submittedBy?: string
  
  // Office review
  corrections: CorrectionRequest[]
  approvedAt?: string
  approvedBy?: string
  
  // Metadata
  createdAt: string
  createdBy: string
  modifiedAt: string
  modifiedBy: string
}

export interface ValidationWaiver {
  id: string
  field: string
  reason: string
  waivedAt: string
  waivedBy: string
}

export interface CorrectionRequest {
  id: string
  field: string
  category?: ChecklistCategory
  measurementType?: MeasurementType
  photoId?: string
  notes: string
  requestedAt: string
  requestedBy: string
  resolvedAt?: string
  resolvedBy?: string
  resolution?: string
}

// Report types
export type ReportStatus = 
  | 'Draft'
  | 'In Review'
  | 'Approved'
  | 'Delivered'
  | 'Archived'

export interface ReportSection {
  id: string
  title: string
  content: string
  photos: string[] // Photo IDs
  autoGeneratedFrom?: ChecklistCategory
  isEdited: boolean
}

export const REPORT_SECTION_TYPES = [
  'interior_coatings',
  'exterior_coatings',
  'foundation',
  'access_hatches',
  'roof_vent',
  'fixed_ladder',
  'overflow',
] as const

export type ReportSectionType = typeof REPORT_SECTION_TYPES[number]

export interface ReportRecommendation {
  id: string
  title: string
  description: string
  priority: 'Critical' | 'High' | 'Medium' | 'Low'
  type: 'Immediate Repair' | 'Scheduled Repair' | 'Coating' | 'Full Rehabilitation' | 'Monitoring' | 'No Action'
  estimatedCostLow?: number
  estimatedCostHigh?: number
  timeframe?: string
  area?: string
  photos: string[] // Photo IDs
  oshaReference?: string
  awwaReference?: string
  isDraft: boolean // True until human-approved
  linkedProposalId?: string
}

export interface FacilityReport {
  name: string
  inspectionId: string
  customer: string
  customerName: string
  site: string
  siteName: string
  tank: string
  tankName: string
  inspectionDate: string
  reportDate: string
  status: ReportStatus
  owner: string
  ownerName: string
  
  // Sections
  sections: ReportSection[]
  
  // Recommendations
  recommendations: ReportRecommendation[]
  
  // Approval workflow
  approvedAt?: string
  approvedBy?: string
  approvedByName?: string
  deliveredAt?: string
  deliveredTo?: string
  
  // Linked opportunities
  linkedProposals: string[]
  
  // Metadata
  createdAt: string
  modifiedAt: string
  version: number
}

// User role for view switching
export type InspectionUserRole = 'field' | 'office'

// Queue filters
export interface InspectionQueueFilters {
  customer?: string
  site?: string
  crew?: string
  status?: InspectionStatus
  dateFrom?: string
  dateTo?: string
}

export interface ReportQueueFilters {
  customer?: string
  site?: string
  status?: ReportStatus
  owner?: string
  dateFrom?: string
  dateTo?: string
}
