// Mock pipeline data matching the visual design

import type { PipelineProposal, PipelineOwner, PipelineStatus } from '@/types/pipeline'

// Pipeline owners
export const pipelineOwners: PipelineOwner[] = [
  { id: 'ron', name: 'Ron', initials: 'R' },
  { id: 'joshua', name: 'Joshua', initials: 'JC' },
  { id: 'mike', name: 'Mike', initials: 'MT' },
  { id: 'curtis', name: 'Curtis', initials: 'CM' },
]

export const mockPipelineProposals: PipelineProposal[] = [
  // Lead column
  {
    name: 'PROP-2024-001',
    proposal_number: 'PROP-2024-001',
    customer: 'CUST-001',
    customer_name: 'City of Springfield',
    site: 'SITE-001',
    site_name: 'Tower #2',
    tank_name: 'Tower #2',
    proposal_type: 'Negotiated',
    status: 'Lead',
    title: 'Visual Inspection',
    scope_summary: 'Visual Inspection',
    total: 1100,
    age_days: 4,
    days_in_stage: 4,
    is_stale: false,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-002',
    proposal_number: 'PROP-2024-002',
    customer: 'CUST-002',
    customer_name: 'MO DNR — Marshall',
    site: 'SITE-002',
    site_name: 'Standpipe',
    tank_name: 'Standpipe',
    proposal_type: 'Engineered Spec',
    status: 'Lead',
    title: 'Sandblast & Reline',
    scope_summary: 'Sandblast & Reline',
    total: 187000,
    age_days: 18,
    days_in_stage: 18,
    is_stale: true,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-003',
    proposal_number: 'PROP-2024-003',
    customer: 'CUST-003',
    customer_name: 'Neosho Municipal',
    site: 'SITE-003',
    site_name: 'Water Tower #1',
    tank_name: 'Water Tower #1',
    proposal_type: 'Negotiated',
    status: 'Lead',
    title: 'Washout & Inspection — Standpipe',
    scope_summary: 'Washout & Inspection — Standpipe',
    total: 2800,
    age_days: 2,
    days_in_stage: 2,
    is_stale: false,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Inspection column
  {
    name: 'PROP-2024-004',
    proposal_number: 'PROP-2024-004',
    customer: 'CUST-004',
    customer_name: 'City of Joplin',
    site: 'SITE-004',
    site_name: 'Tower #4 — Azure Lane',
    tank_name: 'Tower #4 — Azure Lane',
    proposal_type: 'Negotiated',
    status: 'Inspection',
    title: 'Washout & Inspection — Standpipe',
    scope_summary: 'Washout & Inspection — Standpipe',
    total: 2500,
    age_days: 3,
    days_in_stage: 3,
    is_stale: false,
    owner: 'curtis',
    owner_name: 'Curtis',
    owner_initials: 'CM',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-005',
    proposal_number: 'PROP-2024-005',
    customer: 'CUST-005',
    customer_name: 'Branson Water',
    site: 'SITE-005',
    site_name: 'Clear Well',
    tank_name: 'Clear Well',
    proposal_type: 'Negotiated',
    status: 'Inspection',
    title: 'Washout & Inspection — Clear Well',
    scope_summary: 'Washout & Inspection — Clear Well',
    total: 5950,
    age_days: 12,
    days_in_stage: 12,
    is_stale: true,
    owner: 'curtis',
    owner_name: 'Curtis',
    owner_initials: 'CM',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-006',
    proposal_number: 'PROP-2024-006',
    customer: 'CUST-006',
    customer_name: 'Monett Utilities',
    site: 'SITE-006',
    site_name: 'North Tank',
    tank_name: 'North Tank',
    proposal_type: 'Negotiated',
    status: 'Inspection',
    title: 'Visual Inspection',
    scope_summary: 'Visual Inspection',
    total: 1100,
    age_days: 5,
    days_in_stage: 5,
    is_stale: false,
    owner: 'mike',
    owner_name: 'Mike',
    owner_initials: 'MT',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Proposal column
  {
    name: 'PROP-2024-007',
    proposal_number: 'PROP-2024-007',
    customer: 'CUST-007',
    customer_name: 'Town of Lebanon',
    site: 'SITE-007',
    site_name: 'Hilltop Tank',
    tank_name: 'Hilltop Tank',
    proposal_type: 'Negotiated',
    status: 'Proposal',
    title: 'Maintenance Coating',
    scope_summary: 'Maintenance Coating',
    total: 14200,
    age_days: 8,
    days_in_stage: 8,
    is_stale: false,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-008',
    proposal_number: 'PROP-2024-008',
    customer: 'CUST-008',
    customer_name: 'AR Highway Dept',
    site: 'SITE-008',
    site_name: 'Site 47',
    tank_name: 'Site 47',
    proposal_type: 'Engineered Spec',
    status: 'Proposal',
    title: 'Sandblast & Reline',
    scope_summary: 'Sandblast & Reline',
    total: 312000,
    age_days: 22,
    days_in_stage: 22,
    is_stale: true,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-009',
    proposal_number: 'PROP-2024-009',
    customer: 'CUST-009',
    customer_name: 'Pittsburg Township',
    site: 'SITE-009',
    site_name: 'Main Tower',
    tank_name: 'Main Tower',
    proposal_type: 'Negotiated',
    status: 'Proposal',
    title: 'Washout & Inspection — Standpipe',
    scope_summary: 'Washout & Inspection — Standpipe',
    total: 3200,
    age_days: 14,
    days_in_stage: 14,
    is_stale: true,
    owner: 'joshua',
    owner_name: 'Joshua',
    owner_initials: 'JC',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Scheduled column
  {
    name: 'PROP-2024-010',
    proposal_number: 'PROP-2024-010',
    customer: 'CUST-010',
    customer_name: 'City of Carthage',
    site: 'SITE-010',
    site_name: 'East Tower',
    tank_name: 'East Tower',
    proposal_type: 'Negotiated',
    status: 'Scheduled',
    title: 'Washout & Inspection — Standpipe',
    scope_summary: 'Washout & Inspection — Standpipe',
    total: 2500,
    age_days: 6,
    days_in_stage: 6,
    is_stale: false,
    owner: 'mike',
    owner_name: 'Mike',
    owner_initials: 'MT',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-011',
    proposal_number: 'PROP-2024-011',
    customer: 'CUST-011',
    customer_name: 'OK Rural Water',
    site: 'SITE-011',
    site_name: 'Tank 12',
    tank_name: 'Tank 12',
    proposal_type: 'Engineered Spec',
    status: 'Scheduled',
    title: 'Maintenance Coating',
    scope_summary: 'Maintenance Coating',
    total: 48000,
    age_days: 4,
    days_in_stage: 4,
    is_stale: false,
    owner: 'mike',
    owner_name: 'Mike',
    owner_initials: 'MT',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // In Progress column
  {
    name: 'PROP-2024-012',
    proposal_number: 'PROP-2024-012',
    customer: 'CUST-012',
    customer_name: 'Joplin Industrial Park',
    site: 'SITE-012',
    site_name: 'Process Tank',
    tank_name: 'Process Tank',
    proposal_type: 'Negotiated',
    status: 'In Progress',
    title: 'Leak/Weld Repair',
    scope_summary: 'Leak/Weld Repair',
    total: 0,
    age_days: 0,
    days_in_stage: 0,
    is_stale: false,
    owner: 'mike',
    owner_name: 'Mike',
    owner_initials: 'MT',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-013',
    proposal_number: 'PROP-2024-013',
    customer: 'CUST-013',
    customer_name: 'KS Municipal',
    site: 'SITE-013',
    site_name: 'Standpipe #3',
    tank_name: 'Standpipe #3',
    proposal_type: 'Engineered Spec',
    status: 'In Progress',
    title: 'Sandblast & Reline',
    scope_summary: 'Sandblast & Reline',
    total: 0,
    age_days: 0,
    days_in_stage: 0,
    is_stale: false,
    owner: 'mike',
    owner_name: 'Mike',
    owner_initials: 'MT',
    creation: '',
    modified: '',
    docstatus: 0,
    modified_by: '',
    bonding_required: 0,
    prevailing_wage: 0,
  },
]

// Helper to get proposals by status
export function getProposalsByStatus(status: PipelineStatus): PipelineProposal[] {
  return mockPipelineProposals.filter(p => p.status === status)
}

// Helper to get pipeline summary
export function getPipelineSummary() {
  const active = mockPipelineProposals.filter(p => 
    ['Lead', 'Inspection', 'Proposal', 'Scheduled', 'In Progress'].includes(p.status)
  )
  
  const engineered = active.filter(p => p.proposal_type === 'Engineered Spec')
  const negotiated = active.filter(p => p.proposal_type === 'Negotiated')
  
  return {
    totalActive: active.length,
    totalValue: active.reduce((sum, p) => sum + (p.total || 0), 0),
    engineeredCount: engineered.length,
    engineeredValue: engineered.reduce((sum, p) => sum + (p.total || 0), 0),
    negotiatedCount: negotiated.length,
    negotiatedValue: negotiated.reduce((sum, p) => sum + (p.total || 0), 0),
    staleCount: active.filter(p => p.is_stale).length,
  }
}

// Helper to get summary by status
export function getSummaryByStatus(status: PipelineStatus) {
  const proposals = getProposalsByStatus(status)
  return {
    count: proposals.length,
    value: proposals.reduce((sum, p) => sum + (p.total || 0), 0),
  }
}
