// Extended mock data for pipeline

import type { PipelineProposal } from '@/types/pipeline'

function daysAgo(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString().split('T')[0]
}

function daysFromNow(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().split('T')[0]
}

export const mockPipelineProposals: PipelineProposal[] = [
  // Draft
  {
    name: 'PROP-2024-001',
    proposal_number: 'PROP-2024-001',
    customer: 'CUST-003',
    customer_name: 'Riverside Water District',
    site: 'SITE-004',
    site_name: 'Riverside Hilltop Station',
    tank: 'TANK-004',
    proposal_type: 'Negotiated',
    status: 'Draft',
    title: 'Comprehensive 5-Year Inspection',
    scope_of_work: 'Comprehensive 5-year inspection with ROV interior survey.',
    total: 18500,
    valid_until: daysFromNow(60),
    prepared_by: 'USER-001',
    age_days: 5,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(5),
    modified: daysAgo(1),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-002',
    proposal_number: 'PROP-2024-002',
    customer: 'CUST-005',
    customer_name: 'Valley View Water Authority',
    site: 'SITE-005',
    site_name: 'Valley View Tower #1',
    proposal_type: 'Engineered Spec',
    status: 'Draft',
    title: 'Full Exterior Recoat',
    scope_of_work: 'Complete exterior surface preparation and coating application per AWWA D102.',
    total: 425000,
    valid_until: daysFromNow(90),
    prepared_by: 'USER-002',
    bid_due_date: daysFromNow(21),
    age_days: 3,
    is_stale: false,
    owner_name: 'Sarah Johnson',
    creation: daysAgo(3),
    modified: daysAgo(1),
    docstatus: 0,
    modified_by: 'USER-002',
    owner: 'USER-002',
    bonding_required: 1,
    bond_amount: 42500,
    prevailing_wage: 1,
  },
  // Sent
  {
    name: 'PROP-2024-003',
    proposal_number: 'PROP-2024-003',
    customer: 'CUST-002',
    customer_name: 'Greenville Municipal Utilities',
    site: 'SITE-003',
    site_name: 'Greenville Central Tower',
    tank: 'TANK-003',
    proposal_type: 'Negotiated',
    status: 'Sent',
    title: 'Full Interior/Exterior Recoat',
    scope_of_work: 'Complete exterior and interior recoating of Greenville Spheroid tank.',
    total: 285000,
    valid_until: daysFromNow(45),
    sent_date: daysAgo(15),
    prepared_by: 'USER-001',
    next_follow_up_date: daysFromNow(5),
    age_days: 15,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(20),
    modified: daysAgo(15),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-004',
    proposal_number: 'PROP-2024-004',
    customer: 'CUST-001',
    customer_name: 'City of Springfield Water Department',
    site: 'SITE-002',
    site_name: 'Springfield North Reservoir',
    tank: 'TANK-002',
    proposal_type: 'Engineered Spec',
    status: 'Sent',
    title: 'Reservoir Rehabilitation',
    scope_of_work: 'Interior surface prep, zinc primer, and epoxy topcoat per project specs.',
    total: 892000,
    valid_until: daysFromNow(30),
    sent_date: daysAgo(45),
    prepared_by: 'USER-002',
    bid_due_date: daysAgo(30),
    bid_opening_date: daysAgo(25),
    engineer_of_record: 'Burns Engineering',
    next_follow_up_date: daysAgo(5),
    age_days: 45,
    is_stale: false, // Engineered has 60 day threshold
    owner_name: 'Sarah Johnson',
    creation: daysAgo(50),
    modified: daysAgo(45),
    docstatus: 0,
    modified_by: 'USER-002',
    owner: 'USER-002',
    bonding_required: 1,
    bond_amount: 89200,
    prevailing_wage: 1,
  },
  // Follow-Up Due
  {
    name: 'PROP-2024-005',
    proposal_number: 'PROP-2024-005',
    customer: 'CUST-004',
    customer_name: 'Oakmont Township',
    site: 'SITE-006',
    site_name: 'Oakmont Main Tower',
    proposal_type: 'Negotiated',
    status: 'Follow-Up Due',
    title: 'Annual Inspection',
    scope_of_work: 'Annual exterior visual and interior ROV inspection with report.',
    total: 8500,
    valid_until: daysFromNow(15),
    sent_date: daysAgo(35),
    prepared_by: 'USER-001',
    next_follow_up_date: daysAgo(2),
    last_follow_up_date: daysAgo(10),
    follow_up_notes: 'Left voicemail. Waiting for callback from budget committee.',
    age_days: 35,
    is_stale: true, // Over 30 days for Negotiated
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(40),
    modified: daysAgo(10),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2024-006',
    proposal_number: 'PROP-2024-006',
    customer: 'CUST-002',
    customer_name: 'Greenville Municipal Utilities',
    site: 'SITE-003',
    site_name: 'Greenville Central Tower',
    proposal_type: 'Negotiated',
    status: 'Follow-Up Due',
    title: 'Emergency Leak Repair',
    scope_of_work: 'Locate and repair bowl seam leak with weld overlay.',
    total: 32000,
    valid_until: daysFromNow(7),
    sent_date: daysAgo(25),
    prepared_by: 'USER-001',
    next_follow_up_date: daysAgo(1),
    age_days: 25,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(28),
    modified: daysAgo(5),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Pending Board Approval
  {
    name: 'PROP-2024-007',
    proposal_number: 'PROP-2024-007',
    customer: 'CUST-001',
    customer_name: 'City of Springfield Water Department',
    site: 'SITE-001',
    site_name: 'Springfield Main Water Tower',
    tank: 'TANK-001',
    proposal_type: 'Negotiated',
    status: 'Pending Board Approval',
    title: 'Exterior Touch-Up Coating',
    scope_of_work: 'Spot prep and coating of rust areas identified in 2023 inspection.',
    total: 45000,
    valid_until: daysFromNow(30),
    sent_date: daysAgo(60),
    prepared_by: 'USER-002',
    next_follow_up_date: daysFromNow(14),
    follow_up_notes: 'Board meeting scheduled for next month. Contact says likely approval.',
    age_days: 60,
    is_stale: true,
    owner_name: 'Sarah Johnson',
    creation: daysAgo(65),
    modified: daysAgo(5),
    docstatus: 0,
    modified_by: 'USER-002',
    owner: 'USER-002',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Won
  {
    name: 'PROP-2023-015',
    proposal_number: 'PROP-2023-015',
    customer: 'CUST-001',
    customer_name: 'City of Springfield Water Department',
    site: 'SITE-001',
    site_name: 'Springfield Main Water Tower',
    tank: 'TANK-001',
    proposal_type: 'Engineered Spec',
    status: 'Won',
    title: 'Exterior Rust Repair',
    scope_of_work: 'Exterior rust spot repair and touch-up coating.',
    total: 45000,
    valid_until: daysAgo(30),
    sent_date: daysAgo(120),
    won_date: daysAgo(90),
    prepared_by: 'USER-001',
    age_days: 120,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(125),
    modified: daysAgo(90),
    docstatus: 1,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  {
    name: 'PROP-2023-018',
    proposal_number: 'PROP-2023-018',
    customer: 'CUST-003',
    customer_name: 'Riverside Water District',
    site: 'SITE-004',
    site_name: 'Riverside Hilltop Station',
    proposal_type: 'Negotiated',
    status: 'Won',
    title: 'Interior Washout',
    scope_of_work: 'Complete interior washout and sediment removal.',
    total: 12000,
    valid_until: daysAgo(45),
    sent_date: daysAgo(100),
    won_date: daysAgo(75),
    prepared_by: 'USER-002',
    age_days: 100,
    is_stale: false,
    owner_name: 'Sarah Johnson',
    creation: daysAgo(105),
    modified: daysAgo(75),
    docstatus: 1,
    modified_by: 'USER-002',
    owner: 'USER-002',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Lost
  {
    name: 'PROP-2023-012',
    proposal_number: 'PROP-2023-012',
    customer: 'CUST-004',
    customer_name: 'Oakmont Township',
    site: 'SITE-006',
    site_name: 'Oakmont Main Tower',
    proposal_type: 'Engineered Spec',
    status: 'Lost',
    title: 'Full Rehabilitation',
    scope_of_work: 'Complete tank rehabilitation including structural repairs and recoating.',
    total: 650000,
    valid_until: daysAgo(90),
    sent_date: daysAgo(180),
    lost_date: daysAgo(120),
    lost_reason: 'Went with competitor',
    competitor: 'Tank Pros Inc.',
    prepared_by: 'USER-001',
    age_days: 180,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(185),
    modified: daysAgo(120),
    docstatus: 2,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 1,
    prevailing_wage: 1,
  },
  // Expired
  {
    name: 'PROP-2023-008',
    proposal_number: 'PROP-2023-008',
    customer: 'CUST-005',
    customer_name: 'Valley View Water Authority',
    site: 'SITE-005',
    site_name: 'Valley View Tower #1',
    proposal_type: 'Negotiated',
    status: 'Expired',
    title: 'Annual Inspection',
    scope_of_work: 'Annual visual inspection with report.',
    total: 6500,
    valid_until: daysAgo(60),
    sent_date: daysAgo(150),
    prepared_by: 'USER-002',
    age_days: 150,
    is_stale: false,
    owner_name: 'Sarah Johnson',
    creation: daysAgo(155),
    modified: daysAgo(60),
    docstatus: 2,
    modified_by: 'USER-002',
    owner: 'USER-002',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Dormant
  {
    name: 'PROP-2022-025',
    proposal_number: 'PROP-2022-025',
    customer: 'CUST-002',
    customer_name: 'Greenville Municipal Utilities',
    site: 'SITE-003',
    site_name: 'Greenville Central Tower',
    proposal_type: 'Engineered Spec',
    status: 'Dormant',
    title: 'Interior Recoat',
    scope_of_work: 'Complete interior surface prep and epoxy coating.',
    total: 185000,
    valid_until: daysAgo(365),
    sent_date: daysAgo(450),
    prepared_by: 'USER-001',
    notes: 'Customer postponed due to budget. Revisit in Q2 2024.',
    age_days: 450,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(455),
    modified: daysAgo(365),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
  // Revived from Dormant
  {
    name: 'PROP-2024-008',
    proposal_number: 'PROP-2024-008',
    customer: 'CUST-002',
    customer_name: 'Greenville Municipal Utilities',
    site: 'SITE-003',
    site_name: 'Greenville Central Tower',
    proposal_type: 'Engineered Spec',
    status: 'Sent',
    title: 'Interior Recoat (Revised)',
    scope_of_work: 'Complete interior surface prep and epoxy coating. Updated pricing from 2022 proposal.',
    total: 198000,
    valid_until: daysFromNow(60),
    sent_date: daysAgo(10),
    prepared_by: 'USER-001',
    next_follow_up_date: daysFromNow(7),
    is_revived: true,
    original_proposal: 'PROP-2022-025',
    age_days: 10,
    is_stale: false,
    owner_name: 'Mike Thompson',
    owner_avatar: '/avatars/mike.jpg',
    creation: daysAgo(12),
    modified: daysAgo(10),
    docstatus: 0,
    modified_by: 'USER-001',
    owner: 'USER-001',
    bonding_required: 0,
    prevailing_wage: 0,
  },
]

// Helper to get proposals by status
export function getProposalsByStatus(status: string): PipelineProposal[] {
  return mockPipelineProposals.filter(p => p.status === status)
}

// Helper to get pipeline summary
export function getPipelineSummary() {
  const active = mockPipelineProposals.filter(p => 
    ['Draft', 'Sent', 'Follow-Up Due', 'Pending Board Approval'].includes(p.status)
  )
  
  const engineered = active.filter(p => p.proposal_type === 'Engineered Spec')
  const negotiated = active.filter(p => p.proposal_type === 'Negotiated')
  
  return {
    totalActive: active.length,
    totalValue: active.reduce((sum, p) => sum + (p.total || 0), 0),
    engineeredCount: engineered.length,
    engineeredValue: engineered.reduce((sum, p) => sum + (p.total || 0), 0),
    negotiatedCount: negotiated.length,
    negotiatedValue: negotiated.reduce((sum, p) => sum + (p.total || 0), 0),
    staleCount: active.filter(p => p.is_stale).length,
  }
}
